YT_IDS_UNCHECK = 'youtube_data//youtube_files//yt_ids_uncheck.csv'
YT_IDS_CHECK = 'youtube_data//youtube_files//yt_ids_check.csv'
YT_CHANNELS = 'youtube_data//youtube_files//yt_channels_info.csv'
YT_API_CHANNELS= 'https://www.googleapis.com/youtube/v3/channels'
YT_API_PLAYLISTS='https://www.googleapis.com/youtube/v3/playlists'
YT_APIKEY = 'YOUTUBE_CREDENTIAL'
