name: Proceso XML Automático

variables:
  CARPETA_ORIGEN: ../../files
  CARPETA_DESTINO: automatizacion_files
  CARPETA_SCRIPTS: scripts
  CARPETA_CONSULTAS: ../../consultas
  NOMBRE_ARCHIVO: categorias_filtradas
  ARCHIVO_ORIGEN: ${variables.CARPETA_ORIGEN}/${variables.NOMBRE_ARCHIVO}
  ARCHIVO_GENERADO: ${variables.CARPETA_DESTINO}/${variables.NOMBRE_ARCHIVO}

on:
  push:
    branches:
      - AutomatizacionXMLYahoo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils trang unzip
          wget https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE12-4/SaxonHE12-4J.zip
          unzip SaxonHE12-4J.zip -d SaxonJAR

      - name: Preparar archivos
        run: |
          cd scripts/automatizacion
          mkdir -p ${variables.CARPETA_DESTINO}
          cp ${variables.ARCHIVO_ORIGEN}.xml ${variables.ARCHIVO_GENERADO}.xml
          cp ${variables.ARCHIVO_ORIGEN}.xslt ${variables.ARCHIVO_GENERADO}.xslt
          touch ${variables.ARCHIVO_GENERADO}.dtd

      - name: Crear DTD
        run: |
          trang -I xml -O dtd ${variables.ARCHIVO_GENERADO}.xml ${variables.ARCHIVO_GENERADO}.dtd

      - name: Agregar referencia DTD
        run: |
          javac ${variables.CARPETA_SCRIPTS}/add_reference_dtd.java
          java -cp ${variables.CARPETA_SCRIPTS} add_reference_dtd ${variables.ARCHIVO_GENERADO}.xml ${variables.NOMBRE_ARCHIVO}.dtd

      - name: Crear archivo HTML
        run: |
          java -jar SaxonJAR/saxon-he-12.4.jar -s:${ARCHIVO_GENERADO}.xml -xsl:${ARCHIVO_ORIGEN}.xslt -o:${ARCHIVO_GENERADO}XSLT.html

      - name: Ejecutar consultas XQuery
        run: |
          javac -cp SaxonJAR/saxon-he-12.4.jar -Xdiags:verbose ${CARPETA_SCRIPTS}/XQueryExecutor.java
          java -cp ${CARPETA_SCRIPTS}:SaxonJAR/saxon-he-12.4.jar XQueryExecutor ${CARPETA_CONSULTAS}/consulta_1.txt ${ARCHIVO_GENERADO}.xml
          java -cp ${CARPETA_SCRIPTS}:SaxonJAR/saxon-he-12.4.jar XQueryExecutor ${CARPETA_CONSULTAS}/consulta_2.txt ${ARCHIVO_GENERADO}.xml
          java -cp ${CARPETA_SCRIPTS}:SaxonJAR/saxon-he-12.4.jar XQueryExecutor ${CARPETA_CONSULTAS}/consulta_3.txt ${ARCHIVO_GENERADO}.xml
